### ISSUE TITLE
Authentication error when attempting to run example

### ISSUE THREAD

**Issue by CDaut** [kit-sdq/artemis_client#9]
What I did: 
- `python3 trigger_all.py`
- Enter the credentials

I got the following error message:
```
Traceback (most recent call last):
  File "/home/clemens/repositorys/artemistats/venv/lib/python3.10/site-packages/artemis_client/session.py", line 157, in _request_endpoint
    resp = await self._get_session().request(method, endpoint, **kwargs)
  File "/home/clemens/repositorys/artemistats/venv/lib/python3.10/site-packages/aiohttp/client.py", line 643, in _request
    resp.raise_for_status()
  File "/home/clemens/repositorys/artemistats/venv/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1005, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 401, message='', url=URL('https://artemis-test.ipd.kit.edu/api/courses?onlyActive=false')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/clemens/repositorys/artemistats/artemis_client/examples/artemis_client_trigger_all/trigger_all.py", line 77, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/clemens/repositorys/artemistats/artemis_client/examples/artemis_client_trigger_all/trigger_all.py", line 33, in main
    courses = [x async for x in session.course.get_courses()]
  File "/home/clemens/repositorys/artemistats/artemis_client/examples/artemis_client_trigger_all/trigger_all.py", line 33, in <listcomp>
    courses = [x async for x in session.course.get_courses()]
  File "/home/clemens/repositorys/artemistats/venv/lib/python3.10/site-packages/artemis_client/managers/course.py", line 31, in get_courses
    resp = await self._session.get_api_endpoint("/courses", params=params)
  File "/home/clemens/repositorys/artemistats/venv/lib/python3.10/site-packages/artemis_client/session.py", line 105, in get_api_endpoint
    return await self._request_api_endpoint("get", api_endpoint, **kwargs)
  File "/home/clemens/repositorys/artemistats/venv/lib/python3.10/site-packages/artemis_client/session.py", line 174, in _request_api_endpoint
    return await self._request_endpoint(method, "/api" + api_endpoint, **kwargs)
  File "/home/clemens/repositorys/artemistats/venv/lib/python3.10/site-packages/artemis_client/session.py", line 165, in _request_endpoint
    self._token = await self._login()
  File "/home/clemens/repositorys/artemistats/venv/lib/python3.10/site-packages/artemis_client/session.py", line 145, in _login
    return resp.headers[AUTHORIZATION_HEADER]
KeyError: 'authorization'
```
From the error message I gather that it has something to do with the authentication when attempting to get the courses, which is curious because I verified the credentials in the Browser twice and the artemis client is able to construct a Session.

**Comment by Luro02** [comment]
The session is constructed even when the credentials are not valid. The code only makes a login request when an endpoint is called.

To troubleshoot the issue, you could first try to bypass the login code, with something like this:
```diff
import getpass
import asyncio
import os
+import json

...

+cookies = json.load(open("cookies.json"), encoding="utf-8", mode="r")
+bearer = "Bearer eyAAAAAAAAAAAAAAAAAA.eyAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"

async def main():
    async with artemis_client.ArtemisSession(
        artemis_url, username, password
    ) as session:
+       session._get_session().cookie_jar.update_cookies(cookies)
+       session._get_session().headers["Authorization"] = bearer
        clear()

...
```
Note: You must change the bearer string to your own bearer token.

### Obtaining the bearer token:
The token can be obtained through your browser by
1. opening the inspector and the network tab, through which requests can be inspected.
2. When you open the artemis website now, new requests will appear in the tab.
3. Go through the list and look in the header tab under `Request Header`. There should be an `Authorization` key, which will have the Bearer token as its value. Note that `Bearer ` is part of the token and not optional, also take care to select the parts before the `.` and after.
4. The token is not sent with every request, so you might have to look through a few until you find one with the token. (for me, the first request with the token was `en.json?_=....`)

### Cookies
Recently the authentication code for artemis has changed a few times. One instance used cookies, another the bearer token. To be safe, I included the code for cookies as well.

You should check if there are any cookies set, and if so add them to the JSON as a key-value pair like this:
```json
{
    "JSESSIONID": "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD"
}
```
**Important**: the code will fail if the `cookies.json` file is not present, so either remove those parts or create `cookies.json` file with this content: `{}`

### Evaluating the results

If the script now magically works, the login code of this library is broken. Otherwise, you might
be missing login credentials or Artemis is giving bad error messages for other problems like missing permissions.

A 401 status code normally implies that your credentials are not valid.
